/**
 * Generates `components/iee/art-manifest.ts` from what is actually in
 * `public/iee/`.
 *
 * A manifest exists at all because a browser cannot ask whether a file is
 * there: a component that guessed a path would render a broken image and a 404
 * for every entry without art.
 *
 * It is *generated* rather than hand-maintained because the first version was
 * hand-maintained, and the very first person to add artwork could not find the
 * list to edit. That is a design defect, not a reading failure — so the list
 * moved out of the way. Adding art is now: drop the file, run this.
 *
 * Editing the generated file by hand is pointless; the next run overwrites it,
 * and `components/iee/IeeArt.test.tsx` fails while it is stale.
 *
 *   pnpm iee:art
 */
import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

export const ART_KINDS = ["items", "effects"] as const;
export type ArtFolder = (typeof ART_KINDS)[number];

const PUBLIC_DIR = resolve(process.cwd(), "public", "iee");
const OUT = resolve(process.cwd(), "components", "iee", "art-manifest.ts");

/** Keys with artwork in one folder, sorted so the output is stable. */
export function scanArtKeys(kind: ArtFolder, root = PUBLIC_DIR): string[] {
  const dir = resolve(root, kind);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".webp"))
    .map((f) => f.slice(0, -".webp".length))
    .sort();
}

/** The manifest source. Exported so the test can compare without shelling out. */
export function renderManifest(items: readonly string[], effects: readonly string[]): string {
  const list = (keys: readonly string[]) =>
    keys.length === 0 ? "[]" : `[\n${keys.map((k) => `  ${JSON.stringify(k)},`).join("\n")}\n]`;
  return `// GENERATED by \`pnpm iee:art\` from public/iee/. Do not edit by hand.
//
// Add artwork by dropping <catalog key>.webp into public/iee/items/ or
// public/iee/effects/ and re-running the script — see AGENTS.md §5.

export const ART_ITEM_KEYS: readonly string[] = ${list(items)};

export const ART_EFFECT_KEYS: readonly string[] = ${list(effects)};
`;
}

function main() {
  const items = scanArtKeys("items");
  const effects = scanArtKeys("effects");
  writeFileSync(OUT, renderManifest(items, effects), "utf8");
  console.log(
    `iee:art — ${items.length} item + ${effects.length} effect artwork file(s) → components/iee/art-manifest.ts`,
  );
  for (const k of items) console.log(`  item    ${k}`);
  for (const k of effects) console.log(`  effect  ${k}`);
}

/**
 * Only when run as a command, never on import.
 *
 * `IeeArt.test.tsx` imports `renderManifest`/`scanArtKeys` to check the
 * committed manifest is not stale. Without this guard that import *writes* the
 * manifest, so the test compared the file to itself and passed no matter what
 * — which is exactly what a mutation run caught.
 */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
